@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Luis Fernando",
  "email": "luis@mail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luis@mail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta",
  "content": "Teste"
}

###

# @name fetch_recent_question
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/pergunta
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
PUT {{baseUrl}}/questions/337a397f-aa5a-4dc3-93c8-0750dcc7b30f
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta editada",
  "content": "Teste editada"
}

###

# @name delete_question
DELETE {{baseUrl}}/questions/f199abf2-ef98-4d85-8f1a-3a2af51c8336
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/2644776a-bbae-4a83-96a5-9cf5083180b3/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta Teste"
}

###

# @name choose_question_best_answer
PATCH {{baseUrl}}/answers/28384309-c71b-477c-af83-03c6bd65b9b0/choose-as-best
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_answer
PUT {{baseUrl}}/answers/28384309-c71b-477c-af83-03c6bd65b9b0
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta Editada"
}

###

# @name delete_answer
DELETE {{baseUrl}}/answers/28384309-c71b-477c-af83-03c6bd65b9b0
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name comment_on_question
POST {{baseUrl}}/questions/2644776a-bbae-4a83-96a5-9cf5083180b3/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "comentario teste"
}

###

# @name fetch_question_comments
GET {{baseUrl}}/questions/2644776a-bbae-4a83-96a5-9cf5083180b3/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_question_comment
DELETE {{baseUrl}}/questions/comments/cc91a21e-d606-41c2-9ab4-16c73772a2c6
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name comment_on_answer
POST {{baseUrl}}/answers/fc6712bc-6261-4c78-88fe-2ceb7d70e818/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "comentario teste"
}

###

# @name fetch_answer_comments
GET {{baseUrl}}/answers/fc6712bc-6261-4c78-88fe-2ceb7d70e818/comments
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "comentario teste"
}

###

# @name delete_answer_comment
DELETE {{baseUrl}}/answers/comments/b52688b3-3821-4fb3-aaa3-36c79aecc085
Content-Type: application/json
Authorization: Bearer {{authToken}}
