@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Luis Fernando",
  "email": "luis@mail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luis@mail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta teste",
  "content": "Teste"
}

###

# @name fetch_recent_question
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_question
PUT {{baseUrl}}/questions/337a397f-aa5a-4dc3-93c8-0750dcc7b30f
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Pergunta editada",
  "content": "Teste editada"
}

###

# @name delete_question
DELETE  {{baseUrl}}/questions/f199abf2-ef98-4d85-8f1a-3a2af51c8336
Content-Type: application/json
Authorization: Bearer {{authToken}}

{}

###

# @name answer_question
POST {{baseUrl}}/questions/2644776a-bbae-4a83-96a5-9cf5083180b3/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Resposta Teste"
}
